package database;

// Generated 2013/8/24 �W�� 12:19:13 by Hibernate Tools 3.4.0.CR1

/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {

	private int idaddress;
	private String street;
	private String block;
	private String area;
	private String city;
	private String state;
	private String country;
	private Integer contactId;

	public Address() {
	}

	public Address(int idaddress) {
		this.idaddress = idaddress;
	}

	public Address(int idaddress, String street, String block, String area,
			String city, String state, String country, Integer contactId) {
		this.idaddress = idaddress;
		this.street = street;
		this.block = block;
		this.area = area;
		this.city = city;
		this.state = state;
		this.country = country;
		this.contactId = contactId;
	}

	public int getIdaddress() {
		return this.idaddress;
	}

	public void setIdaddress(int idaddress) {
		this.idaddress = idaddress;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getBlock() {
		return this.block;
	}

	public void setBlock(String block) {
		this.block = block;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public Integer getContactId() {
		return this.contactId;
	}

	public void setContactId(Integer contactId) {
		this.contactId = contactId;
	}

}
