package database;

// Generated 2013/8/24 �W�� 12:19:13 by Hibernate Tools 3.4.0.CR1

/**
 * Authority generated by hbm2java
 */
public class Authority implements java.io.Serializable {

	private Integer idauthority;
	private boolean print;
	private boolean execute;
	private boolean insert;
	private boolean edit;
	private boolean delete;
	private boolean confirm;
	private boolean post;

	public Authority() {
	}

	public Authority(boolean print, boolean execute, boolean insert,
			boolean edit, boolean delete, boolean confirm, boolean post) {
		this.print = print;
		this.execute = execute;
		this.insert = insert;
		this.edit = edit;
		this.delete = delete;
		this.confirm = confirm;
		this.post = post;
	}

	public Integer getIdauthority() {
		return this.idauthority;
	}

	public void setIdauthority(Integer idauthority) {
		this.idauthority = idauthority;
	}

	public boolean isPrint() {
		return this.print;
	}

	public void setPrint(boolean print) {
		this.print = print;
	}

	public boolean isExecute() {
		return this.execute;
	}

	public void setExecute(boolean execute) {
		this.execute = execute;
	}

	public boolean isInsert() {
		return this.insert;
	}

	public void setInsert(boolean insert) {
		this.insert = insert;
	}

	public boolean isEdit() {
		return this.edit;
	}

	public void setEdit(boolean edit) {
		this.edit = edit;
	}

	public boolean isDelete() {
		return this.delete;
	}

	public void setDelete(boolean delete) {
		this.delete = delete;
	}

	public boolean isConfirm() {
		return this.confirm;
	}

	public void setConfirm(boolean confirm) {
		this.confirm = confirm;
	}

	public boolean isPost() {
		return this.post;
	}

	public void setPost(boolean post) {
		this.post = post;
	}

}
