package database;

// Generated 2013/8/13 �W�� 12:20:54 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Contact generated by hbm2java
 */
public class Contact implements java.io.Serializable {

	private int idcontact;
	private String name;
	private Set objectbasicdatas = new HashSet(0);

	public Contact() {
	}

	public Contact(int idcontact) {
		this.idcontact = idcontact;
	}

	public Contact(int idcontact, String name, Set objectbasicdatas) {
		this.idcontact = idcontact;
		this.name = name;
		this.objectbasicdatas = objectbasicdatas;
	}

	public int getIdcontact() {
		return this.idcontact;
	}

	public void setIdcontact(int idcontact) {
		this.idcontact = idcontact;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getObjectbasicdatas() {
		return this.objectbasicdatas;
	}

	public void setObjectbasicdatas(Set objectbasicdatas) {
		this.objectbasicdatas = objectbasicdatas;
	}

}
