package database;

// Generated 2013/8/24 �W�� 12:19:13 by Hibernate Tools 3.4.0.CR1

/**
 * Departbasicdata generated by hbm2java
 */
public class Departbasicdata implements java.io.Serializable {

	private String departId;
	private String departAlias;
	private String departFullName;
	private String departEngAlias;
	private String departEngFullName;
	private Character expenseClassId;
	private String parentDepartId;
	private Float effectiveDate;
	private Float lostEffectiveDate;
	private String departIdclassification;

	public Departbasicdata() {
	}

	public Departbasicdata(String departId, String departAlias) {
		this.departId = departId;
		this.departAlias = departAlias;
	}

	public Departbasicdata(String departId, String departAlias,
			String departFullName, String departEngAlias,
			String departEngFullName, Character expenseClassId,
			String parentDepartId, Float effectiveDate,
			Float lostEffectiveDate, String departIdclassification) {
		this.departId = departId;
		this.departAlias = departAlias;
		this.departFullName = departFullName;
		this.departEngAlias = departEngAlias;
		this.departEngFullName = departEngFullName;
		this.expenseClassId = expenseClassId;
		this.parentDepartId = parentDepartId;
		this.effectiveDate = effectiveDate;
		this.lostEffectiveDate = lostEffectiveDate;
		this.departIdclassification = departIdclassification;
	}

	public String getDepartId() {
		return this.departId;
	}

	public void setDepartId(String departId) {
		this.departId = departId;
	}

	public String getDepartAlias() {
		return this.departAlias;
	}

	public void setDepartAlias(String departAlias) {
		this.departAlias = departAlias;
	}

	public String getDepartFullName() {
		return this.departFullName;
	}

	public void setDepartFullName(String departFullName) {
		this.departFullName = departFullName;
	}

	public String getDepartEngAlias() {
		return this.departEngAlias;
	}

	public void setDepartEngAlias(String departEngAlias) {
		this.departEngAlias = departEngAlias;
	}

	public String getDepartEngFullName() {
		return this.departEngFullName;
	}

	public void setDepartEngFullName(String departEngFullName) {
		this.departEngFullName = departEngFullName;
	}

	public Character getExpenseClassId() {
		return this.expenseClassId;
	}

	public void setExpenseClassId(Character expenseClassId) {
		this.expenseClassId = expenseClassId;
	}

	public String getParentDepartId() {
		return this.parentDepartId;
	}

	public void setParentDepartId(String parentDepartId) {
		this.parentDepartId = parentDepartId;
	}

	public Float getEffectiveDate() {
		return this.effectiveDate;
	}

	public void setEffectiveDate(Float effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	public Float getLostEffectiveDate() {
		return this.lostEffectiveDate;
	}

	public void setLostEffectiveDate(Float lostEffectiveDate) {
		this.lostEffectiveDate = lostEffectiveDate;
	}

	public String getDepartIdclassification() {
		return this.departIdclassification;
	}

	public void setDepartIdclassification(String departIdclassification) {
		this.departIdclassification = departIdclassification;
	}

}
