package database;

// Generated 2013/8/24 �W�� 12:19:13 by Hibernate Tools 3.4.0.CR1

/**
 * Matcode generated by hbm2java
 */
public class Matcode implements java.io.Serializable {

	private String matId;
	private String name;
	private String spec;
	private String unitId;
	private String engName;

	public Matcode() {
	}

	public Matcode(String matId) {
		this.matId = matId;
	}

	public Matcode(String matId, String name, String spec, String unitId,
			String engName) {
		this.matId = matId;
		this.name = name;
		this.spec = spec;
		this.unitId = unitId;
		this.engName = engName;
	}

	public String getMatId() {
		return this.matId;
	}

	public void setMatId(String matId) {
		this.matId = matId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSpec() {
		return this.spec;
	}

	public void setSpec(String spec) {
		this.spec = spec;
	}

	public String getUnitId() {
		return this.unitId;
	}

	public void setUnitId(String unitId) {
		this.unitId = unitId;
	}

	public String getEngName() {
		return this.engName;
	}

	public void setEngName(String engName) {
		this.engName = engName;
	}

}
