package database;

// Generated 2013/8/24 �W�� 12:19:13 by Hibernate Tools 3.4.0.CR1

/**
 * ObjectbasicdataId generated by hbm2java
 */
public class ObjectbasicdataId implements java.io.Serializable {

	private String objectClassId;
	private String objectId;

	public ObjectbasicdataId() {
	}

	public ObjectbasicdataId(String objectClassId, String objectId) {
		this.objectClassId = objectClassId;
		this.objectId = objectId;
	}

	public String getObjectClassId() {
		return this.objectClassId;
	}

	public void setObjectClassId(String objectClassId) {
		this.objectClassId = objectClassId;
	}

	public String getObjectId() {
		return this.objectId;
	}

	public void setObjectId(String objectId) {
		this.objectId = objectId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ObjectbasicdataId))
			return false;
		ObjectbasicdataId castOther = (ObjectbasicdataId) other;

		return ((this.getObjectClassId() == castOther.getObjectClassId()) || (this
				.getObjectClassId() != null
				&& castOther.getObjectClassId() != null && this
				.getObjectClassId().equals(castOther.getObjectClassId())))
				&& ((this.getObjectId() == castOther.getObjectId()) || (this
						.getObjectId() != null
						&& castOther.getObjectId() != null && this
						.getObjectId().equals(castOther.getObjectId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getObjectClassId() == null ? 0 : this.getObjectClassId()
						.hashCode());
		result = 37 * result
				+ (getObjectId() == null ? 0 : this.getObjectId().hashCode());
		return result;
	}

}
