package database;

// Generated 2013/8/24 �W�� 12:19:13 by Hibernate Tools 3.4.0.CR1

/**
 * Objectbasicdata generated by hbm2java
 */
public class Objectbasicdata implements java.io.Serializable {

	private ObjectbasicdataId id;
	private String objectName;
	private String objectNameEng;
	private String companyNo;
	private Integer contactId;

	public Objectbasicdata() {
	}

	public Objectbasicdata(ObjectbasicdataId id) {
		this.id = id;
	}

	public Objectbasicdata(ObjectbasicdataId id, String objectName,
			String objectNameEng, String companyNo, Integer contactId) {
		this.id = id;
		this.objectName = objectName;
		this.objectNameEng = objectNameEng;
		this.companyNo = companyNo;
		this.contactId = contactId;
	}

	public ObjectbasicdataId getId() {
		return this.id;
	}

	public void setId(ObjectbasicdataId id) {
		this.id = id;
	}

	public String getObjectName() {
		return this.objectName;
	}

	public void setObjectName(String objectName) {
		this.objectName = objectName;
	}

	public String getObjectNameEng() {
		return this.objectNameEng;
	}

	public void setObjectNameEng(String objectNameEng) {
		this.objectNameEng = objectNameEng;
	}

	public String getCompanyNo() {
		return this.companyNo;
	}

	public void setCompanyNo(String companyNo) {
		this.companyNo = companyNo;
	}

	public Integer getContactId() {
		return this.contactId;
	}

	public void setContactId(Integer contactId) {
		this.contactId = contactId;
	}

}
