package database;

// Generated 2013/8/24 �W�� 12:19:13 by Hibernate Tools 3.4.0.CR1

/**
 * Phone generated by hbm2java
 */
public class Phone implements java.io.Serializable {

	private int idphone;
	private Integer contactId;
	private String number;
	private String type;

	public Phone() {
	}

	public Phone(int idphone) {
		this.idphone = idphone;
	}

	public Phone(int idphone, Integer contactId, String number, String type) {
		this.idphone = idphone;
		this.contactId = contactId;
		this.number = number;
		this.type = type;
	}

	public int getIdphone() {
		return this.idphone;
	}

	public void setIdphone(int idphone) {
		this.idphone = idphone;
	}

	public Integer getContactId() {
		return this.contactId;
	}

	public void setContactId(Integer contactId) {
		this.contactId = contactId;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
