package database;

// Generated 2013/8/24 �W�� 12:19:13 by Hibernate Tools 3.4.0.CR1

/**
 * Programs generated by hbm2java
 */
public class Programs implements java.io.Serializable {

	private String programId;
	private String programName;

	public Programs() {
	}

	public Programs(String programId, String programName) {
		this.programId = programId;
		this.programName = programName;
	}

	public String getProgramId() {
		return this.programId;
	}

	public void setProgramId(String programId) {
		this.programId = programId;
	}

	public String getProgramName() {
		return this.programName;
	}

	public void setProgramName(String programName) {
		this.programName = programName;
	}

}
