package database;

// Generated 2013/8/16 �U�� 10:29:46 by Hibernate Tools 3.4.0.CR1

/**
 * PurchaseorderDetailsId generated by hbm2java
 */
public class PurchaseorderDetailsId implements java.io.Serializable {

	private Purchaseorder purchaseorder;
	private String sequNo;

	public PurchaseorderDetailsId() {
	}

	public PurchaseorderDetailsId(Purchaseorder purchaseorder, String sequNo) {
		this.purchaseorder = purchaseorder;
		this.sequNo = sequNo;
	}

	public Purchaseorder getPurchaseorder() {
		return this.purchaseorder;
	}

	public void setPurchaseorder(Purchaseorder purchaseorder) {
		this.purchaseorder = purchaseorder;
	}

	public String getSequNo() {
		return this.sequNo;
	}

	public void setSequNo(String sequNo) {
		this.sequNo = sequNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PurchaseorderDetailsId))
			return false;
		PurchaseorderDetailsId castOther = (PurchaseorderDetailsId) other;

		return ((this.getPurchaseorder() == castOther.getPurchaseorder()) || (this
				.getPurchaseorder() != null
				&& castOther.getPurchaseorder() != null && this
				.getPurchaseorder().equals(castOther.getPurchaseorder())))
				&& ((this.getSequNo() == castOther.getSequNo()) || (this
						.getSequNo() != null && castOther.getSequNo() != null && this
						.getSequNo().equals(castOther.getSequNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getPurchaseorder() == null ? 0 : this.getPurchaseorder()
						.hashCode());
		result = 37 * result
				+ (getSequNo() == null ? 0 : this.getSequNo().hashCode());
		return result;
	}

}
