package database;

// Generated 2013/8/24 �W�� 12:19:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PurchaseorderDetails generated by hbm2java
 */
public class PurchaseorderDetails implements java.io.Serializable {

	private Integer id;
	private RequisitionDetails requisitionDetails;
	private Purchaseorder purchaseorder;
	private Character purOrderKind;
	private String purOrderCode;
	private String purOrderSpeci;
	private String purOrderPack;
	private String purOrderUnit;
	private Float purOrderQuantity;
	private Float purOrderUnitPrice;
	private Character purOrderTaxRate;
	private Float receivedQuantity;
	private Float acceptQuantity;
	private Date estTimeOfArrival;
	private Date actualTimeOfArrival;
	private Date actualTimeOfAccept;
	private String memo;
	private Float acceptDiscountAmt;

	public PurchaseorderDetails() {
	}

	public PurchaseorderDetails(Purchaseorder purchaseorder) {
		this.purchaseorder = purchaseorder;
	}

	public PurchaseorderDetails(RequisitionDetails requisitionDetails,
			Purchaseorder purchaseorder, Character purOrderKind,
			String purOrderCode, String purOrderSpeci, String purOrderPack,
			String purOrderUnit, Float purOrderQuantity,
			Float purOrderUnitPrice, Character purOrderTaxRate,
			Float receivedQuantity, Float acceptQuantity,
			Date estTimeOfArrival, Date actualTimeOfArrival,
			Date actualTimeOfAccept, String memo, Float acceptDiscountAmt) {
		this.requisitionDetails = requisitionDetails;
		this.purchaseorder = purchaseorder;
		this.purOrderKind = purOrderKind;
		this.purOrderCode = purOrderCode;
		this.purOrderSpeci = purOrderSpeci;
		this.purOrderPack = purOrderPack;
		this.purOrderUnit = purOrderUnit;
		this.purOrderQuantity = purOrderQuantity;
		this.purOrderUnitPrice = purOrderUnitPrice;
		this.purOrderTaxRate = purOrderTaxRate;
		this.receivedQuantity = receivedQuantity;
		this.acceptQuantity = acceptQuantity;
		this.estTimeOfArrival = estTimeOfArrival;
		this.actualTimeOfArrival = actualTimeOfArrival;
		this.actualTimeOfAccept = actualTimeOfAccept;
		this.memo = memo;
		this.acceptDiscountAmt = acceptDiscountAmt;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public RequisitionDetails getRequisitionDetails() {
		return this.requisitionDetails;
	}

	public void setRequisitionDetails(RequisitionDetails requisitionDetails) {
		this.requisitionDetails = requisitionDetails;
	}

	public Purchaseorder getPurchaseorder() {
		return this.purchaseorder;
	}

	public void setPurchaseorder(Purchaseorder purchaseorder) {
		this.purchaseorder = purchaseorder;
	}

	public Character getPurOrderKind() {
		return this.purOrderKind;
	}

	public void setPurOrderKind(Character purOrderKind) {
		this.purOrderKind = purOrderKind;
	}

	public String getPurOrderCode() {
		return this.purOrderCode;
	}

	public void setPurOrderCode(String purOrderCode) {
		this.purOrderCode = purOrderCode;
	}

	public String getPurOrderSpeci() {
		return this.purOrderSpeci;
	}

	public void setPurOrderSpeci(String purOrderSpeci) {
		this.purOrderSpeci = purOrderSpeci;
	}

	public String getPurOrderPack() {
		return this.purOrderPack;
	}

	public void setPurOrderPack(String purOrderPack) {
		this.purOrderPack = purOrderPack;
	}

	public String getPurOrderUnit() {
		return this.purOrderUnit;
	}

	public void setPurOrderUnit(String purOrderUnit) {
		this.purOrderUnit = purOrderUnit;
	}

	public Float getPurOrderQuantity() {
		return this.purOrderQuantity;
	}

	public void setPurOrderQuantity(Float purOrderQuantity) {
		this.purOrderQuantity = purOrderQuantity;
	}

	public Float getPurOrderUnitPrice() {
		return this.purOrderUnitPrice;
	}

	public void setPurOrderUnitPrice(Float purOrderUnitPrice) {
		this.purOrderUnitPrice = purOrderUnitPrice;
	}

	public Character getPurOrderTaxRate() {
		return this.purOrderTaxRate;
	}

	public void setPurOrderTaxRate(Character purOrderTaxRate) {
		this.purOrderTaxRate = purOrderTaxRate;
	}

	public Float getReceivedQuantity() {
		return this.receivedQuantity;
	}

	public void setReceivedQuantity(Float receivedQuantity) {
		this.receivedQuantity = receivedQuantity;
	}

	public Float getAcceptQuantity() {
		return this.acceptQuantity;
	}

	public void setAcceptQuantity(Float acceptQuantity) {
		this.acceptQuantity = acceptQuantity;
	}

	public Date getEstTimeOfArrival() {
		return this.estTimeOfArrival;
	}

	public void setEstTimeOfArrival(Date estTimeOfArrival) {
		this.estTimeOfArrival = estTimeOfArrival;
	}

	public Date getActualTimeOfArrival() {
		return this.actualTimeOfArrival;
	}

	public void setActualTimeOfArrival(Date actualTimeOfArrival) {
		this.actualTimeOfArrival = actualTimeOfArrival;
	}

	public Date getActualTimeOfAccept() {
		return this.actualTimeOfAccept;
	}

	public void setActualTimeOfAccept(Date actualTimeOfAccept) {
		this.actualTimeOfAccept = actualTimeOfAccept;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public Float getAcceptDiscountAmt() {
		return this.acceptDiscountAmt;
	}

	public void setAcceptDiscountAmt(Float acceptDiscountAmt) {
		this.acceptDiscountAmt = acceptDiscountAmt;
	}

}
