package database;

// Generated 2013/8/24 �W�� 12:19:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Purchaseorder generated by hbm2java
 */
public class Purchaseorder implements java.io.Serializable {

	private Integer purOrderId;
	private String sysId;
	private Date purOrderDate;
	private String purOrderDepartId;
	private String reqObjectId;
	private String purOrderVendor;
	private Character purOrderSalesTerm;
	private Character purOrderPaymentTerm;
	private Character purOrderStatus;
	private String memo;
	private String operationId;
	private String confirmId;
	private Date confirmDate;
	private String updateUserId;
	private Date updateDate;
	private Integer notesMonthPayDate;
	private Integer monthsOfPayment;
	private Set purchaseorderDetailses = new HashSet(0);

	public Purchaseorder() {
	}

	public Purchaseorder(String sysId, Date purOrderDate,
			String purOrderDepartId, String reqObjectId, String purOrderVendor,
			Character purOrderSalesTerm, Character purOrderPaymentTerm,
			Character purOrderStatus, String memo, String operationId,
			String confirmId, Date confirmDate, String updateUserId,
			Date updateDate, Integer notesMonthPayDate,
			Integer monthsOfPayment, Set purchaseorderDetailses) {
		this.sysId = sysId;
		this.purOrderDate = purOrderDate;
		this.purOrderDepartId = purOrderDepartId;
		this.reqObjectId = reqObjectId;
		this.purOrderVendor = purOrderVendor;
		this.purOrderSalesTerm = purOrderSalesTerm;
		this.purOrderPaymentTerm = purOrderPaymentTerm;
		this.purOrderStatus = purOrderStatus;
		this.memo = memo;
		this.operationId = operationId;
		this.confirmId = confirmId;
		this.confirmDate = confirmDate;
		this.updateUserId = updateUserId;
		this.updateDate = updateDate;
		this.notesMonthPayDate = notesMonthPayDate;
		this.monthsOfPayment = monthsOfPayment;
		this.purchaseorderDetailses = purchaseorderDetailses;
	}

	public Integer getPurOrderId() {
		return this.purOrderId;
	}

	public void setPurOrderId(Integer purOrderId) {
		this.purOrderId = purOrderId;
	}

	public String getSysId() {
		return this.sysId;
	}

	public void setSysId(String sysId) {
		this.sysId = sysId;
	}

	public Date getPurOrderDate() {
		return this.purOrderDate;
	}

	public void setPurOrderDate(Date purOrderDate) {
		this.purOrderDate = purOrderDate;
	}

	public String getPurOrderDepartId() {
		return this.purOrderDepartId;
	}

	public void setPurOrderDepartId(String purOrderDepartId) {
		this.purOrderDepartId = purOrderDepartId;
	}

	public String getReqObjectId() {
		return this.reqObjectId;
	}

	public void setReqObjectId(String reqObjectId) {
		this.reqObjectId = reqObjectId;
	}

	public String getPurOrderVendor() {
		return this.purOrderVendor;
	}

	public void setPurOrderVendor(String purOrderVendor) {
		this.purOrderVendor = purOrderVendor;
	}

	public Character getPurOrderSalesTerm() {
		return this.purOrderSalesTerm;
	}

	public void setPurOrderSalesTerm(Character purOrderSalesTerm) {
		this.purOrderSalesTerm = purOrderSalesTerm;
	}

	public Character getPurOrderPaymentTerm() {
		return this.purOrderPaymentTerm;
	}

	public void setPurOrderPaymentTerm(Character purOrderPaymentTerm) {
		this.purOrderPaymentTerm = purOrderPaymentTerm;
	}

	public Character getPurOrderStatus() {
		return this.purOrderStatus;
	}

	public void setPurOrderStatus(Character purOrderStatus) {
		this.purOrderStatus = purOrderStatus;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getOperationId() {
		return this.operationId;
	}

	public void setOperationId(String operationId) {
		this.operationId = operationId;
	}

	public String getConfirmId() {
		return this.confirmId;
	}

	public void setConfirmId(String confirmId) {
		this.confirmId = confirmId;
	}

	public Date getConfirmDate() {
		return this.confirmDate;
	}

	public void setConfirmDate(Date confirmDate) {
		this.confirmDate = confirmDate;
	}

	public String getUpdateUserId() {
		return this.updateUserId;
	}

	public void setUpdateUserId(String updateUserId) {
		this.updateUserId = updateUserId;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Integer getNotesMonthPayDate() {
		return this.notesMonthPayDate;
	}

	public void setNotesMonthPayDate(Integer notesMonthPayDate) {
		this.notesMonthPayDate = notesMonthPayDate;
	}

	public Integer getMonthsOfPayment() {
		return this.monthsOfPayment;
	}

	public void setMonthsOfPayment(Integer monthsOfPayment) {
		this.monthsOfPayment = monthsOfPayment;
	}

	public Set getPurchaseorderDetailses() {
		return this.purchaseorderDetailses;
	}

	public void setPurchaseorderDetailses(Set purchaseorderDetailses) {
		this.purchaseorderDetailses = purchaseorderDetailses;
	}

}
