package database;

// Generated 2013/8/24 �W�� 12:19:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import model.RequisitionModel;

/**
 * RequisitionDetails generated by hbm2java
 */
public class RequisitionDetails implements java.io.Serializable {

	private Integer id;
	private Requisition requisition;
	private String wasteDepartId;
	private Character requKind;
	private String requCode;
	private String requSpeci;
	private String requPack;
	private String requUnit;
	private Float requQuantity;
	private Float orderQuantity;
	private Date estimatedTimeOfArrival;
	private Date deadlineDeliveryDate;
	private Character requStatus;
	private String reqObjectId;
	private String memo;
	private Set purchaseorderDetailses = new HashSet(0);

	public RequisitionDetails() {
	}

	public RequisitionDetails(Requisition requisition) {
		this.requisition = requisition;
	}

	public RequisitionDetails(Requisition requisition, String wasteDepartId,
			Character requKind, String requCode, String requSpeci,
			String requPack, String requUnit, Float requQuantity,
			Float orderQuantity, Date estimatedTimeOfArrival,
			Date deadlineDeliveryDate, Character requStatus,
			String reqObjectId, String memo, Set purchaseorderDetailses) {
		this.requisition = requisition;
		this.wasteDepartId = wasteDepartId;
		this.requKind = requKind;
		this.requCode = requCode;
		this.requSpeci = requSpeci;
		this.requPack = requPack;
		this.requUnit = requUnit;
		this.requQuantity = requQuantity;
		this.orderQuantity = orderQuantity;
		this.estimatedTimeOfArrival = estimatedTimeOfArrival;
		this.deadlineDeliveryDate = deadlineDeliveryDate;
		this.requStatus = requStatus;
		this.reqObjectId = reqObjectId;
		this.memo = memo;
		this.purchaseorderDetailses = purchaseorderDetailses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Requisition getRequisition() {
		return this.requisition;
	}

	public void setRequisition(Requisition requisition) {
		this.requisition = requisition;
	}

	public String getWasteDepartId() {
		return this.wasteDepartId;
	}

	public void setWasteDepartId(String wasteDepartId) {
		this.wasteDepartId = wasteDepartId;
	}

	public Character getRequKind() {
		return this.requKind;
	}

	public void setRequKind(Character requKind) {
		this.requKind = requKind;
	}

	public String getRequCode() {
		return this.requCode;
	}

	public void setRequCode(String requCode) {
		this.requCode = requCode;
	}

	public String getRequSpeci() {
		return this.requSpeci;
	}

	public void setRequSpeci(String requSpeci) {
		this.requSpeci = requSpeci;
	}

	public String getRequPack() {
		return this.requPack;
	}

	public void setRequPack(String requPack) {
		this.requPack = requPack;
	}

	public String getRequUnit() {
		return this.requUnit;
	}

	public void setRequUnit(String requUnit) {
		this.requUnit = requUnit;
	}

	public Float getRequQuantity() {
		return this.requQuantity;
	}

	public void setRequQuantity(Float requQuantity) {
		this.requQuantity = requQuantity;
	}

	public Float getOrderQuantity() {
		return this.orderQuantity;
	}

	public void setOrderQuantity(Float orderQuantity) {
		this.orderQuantity = orderQuantity;
	}

	public Date getEstimatedTimeOfArrival() {
		return this.estimatedTimeOfArrival;
	}

	public void setEstimatedTimeOfArrival(Date estimatedTimeOfArrival) {
		this.estimatedTimeOfArrival = estimatedTimeOfArrival;
	}

	public Date getDeadlineDeliveryDate() {
		return this.deadlineDeliveryDate;
	}

	public void setDeadlineDeliveryDate(Date deadlineDeliveryDate) {
		this.deadlineDeliveryDate = deadlineDeliveryDate;
	}

	public Character getRequStatus() {
		return this.requStatus;
	}

	public void setRequStatus(Character requStatus) {
		this.requStatus = requStatus;
	}

	public String getReqObjectId() {
		return this.reqObjectId;
	}

	public void setReqObjectId(String reqObjectId) {
		this.reqObjectId = reqObjectId;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public Set getPurchaseorderDetailses() {
		return this.purchaseorderDetailses;
	}

	public void setPurchaseorderDetailses(Set purchaseorderDetailses) {
		this.purchaseorderDetailses = purchaseorderDetailses;
	}

	public RequisitionDetails getCurrentDetail() {
		return this;
	}

	public void setCurrentDetail(RequisitionModel requisitionModel) {
		requisitionModel.currentDetail = this;
	}

}
