package database;

// Generated 2013/8/24 �W�� 12:19:13 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Requisition generated by hbm2java
 */
public class Requisition implements java.io.Serializable {

	private Integer requisitionId;
	private String sysId;
	private Date requDate;
	private String requDepartId;
	private String budgetNo;
	private String memo;
	private String operatorId;
	private String confirmId;
	private String updateId;
	private Date confirmDate;
	private Date updateDate;
	private Character mark;
	private Set requisitionDetailses = new HashSet(0);

	public Requisition() {
	}

	public Requisition(String sysId, Date requDate, String requDepartId,
			String budgetNo, String memo, String operatorId, String confirmId,
			String updateId, Date confirmDate, Date updateDate, Character mark,
			Set requisitionDetailses) {
		this.sysId = sysId;
		this.requDate = requDate;
		this.requDepartId = requDepartId;
		this.budgetNo = budgetNo;
		this.memo = memo;
		this.operatorId = operatorId;
		this.confirmId = confirmId;
		this.updateId = updateId;
		this.confirmDate = confirmDate;
		this.updateDate = updateDate;
		this.mark = mark;
		this.requisitionDetailses = requisitionDetailses;
	}

	public Integer getRequisitionId() {
		return this.requisitionId;
	}

	public void setRequisitionId(Integer requisitionId) {
		this.requisitionId = requisitionId;
	}

	public String getSysId() {
		return this.sysId;
	}

	public void setSysId(String sysId) {
		this.sysId = sysId;
	}

	public Date getRequDate() {
		return this.requDate;
	}

	public void setRequDate(Date requDate) {
		this.requDate = requDate;
	}

	public String getRequDepartId() {
		return this.requDepartId;
	}

	public void setRequDepartId(String requDepartId) {
		this.requDepartId = requDepartId;
	}

	public String getBudgetNo() {
		return this.budgetNo;
	}

	public void setBudgetNo(String budgetNo) {
		this.budgetNo = budgetNo;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getOperatorId() {
		return this.operatorId;
	}

	public void setOperatorId(String operatorId) {
		this.operatorId = operatorId;
	}

	public String getConfirmId() {
		return this.confirmId;
	}

	public void setConfirmId(String confirmId) {
		this.confirmId = confirmId;
	}

	public String getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(String updateId) {
		this.updateId = updateId;
	}

	public Date getConfirmDate() {
		return this.confirmDate;
	}

	public void setConfirmDate(Date confirmDate) {
		this.confirmDate = confirmDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Character getMark() {
		return this.mark;
	}

	public void setMark(Character mark) {
		this.mark = mark;
	}

	public Set getRequisitionDetailses() {
		return this.requisitionDetailses;
	}

	public void setRequisitionDetailses(Set requisitionDetailses) {
		this.requisitionDetailses = requisitionDetailses;
	}

}
