package database;

// Generated 2013/8/16 �U�� 10:29:46 by Hibernate Tools 3.4.0.CR1

/**
 * RequisitionDetailsId generated by hbm2java
 */
public class RequisitionDetailsId implements java.io.Serializable {

	private Requisition requisition;
	private String sequNo;

	public RequisitionDetailsId() {
	}

	public RequisitionDetailsId(Requisition requisition, String sequNo) {
		this.requisition = requisition;
		this.sequNo = sequNo;
	}

	public Requisition getRequisition() {
		return this.requisition;
	}

	public void setRequisition(Requisition requisition) {
		this.requisition = requisition;
	}

	public String getSequNo() {
		return this.sequNo;
	}

	public void setSequNo(String sequNo) {
		this.sequNo = sequNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RequisitionDetailsId))
			return false;
		RequisitionDetailsId castOther = (RequisitionDetailsId) other;

		return ((this.getRequisition() == castOther.getRequisition()) || (this
				.getRequisition() != null && castOther.getRequisition() != null && this
				.getRequisition().equals(castOther.getRequisition())))
				&& ((this.getSequNo() == castOther.getSequNo()) || (this
						.getSequNo() != null && castOther.getSequNo() != null && this
						.getSequNo().equals(castOther.getSequNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getRequisition() == null ? 0 : this.getRequisition()
						.hashCode());
		result = 37 * result
				+ (getSequNo() == null ? 0 : this.getSequNo().hashCode());
		return result;
	}

}
