package database;

// Generated 2013/8/24 �W�� 12:19:13 by Hibernate Tools 3.4.0.CR1

/**
 * UserauthorityId generated by hbm2java
 */
public class UserauthorityId implements java.io.Serializable {

	private String programId;
	private String userId;
	private int authorityId;

	public UserauthorityId() {
	}

	public UserauthorityId(String programId, String userId, int authorityId) {
		this.programId = programId;
		this.userId = userId;
		this.authorityId = authorityId;
	}

	public String getProgramId() {
		return this.programId;
	}

	public void setProgramId(String programId) {
		this.programId = programId;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public int getAuthorityId() {
		return this.authorityId;
	}

	public void setAuthorityId(int authorityId) {
		this.authorityId = authorityId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserauthorityId))
			return false;
		UserauthorityId castOther = (UserauthorityId) other;

		return ((this.getProgramId() == castOther.getProgramId()) || (this
				.getProgramId() != null && castOther.getProgramId() != null && this
				.getProgramId().equals(castOther.getProgramId())))
				&& ((this.getUserId() == castOther.getUserId()) || (this
						.getUserId() != null && castOther.getUserId() != null && this
						.getUserId().equals(castOther.getUserId())))
				&& (this.getAuthorityId() == castOther.getAuthorityId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getProgramId() == null ? 0 : this.getProgramId().hashCode());
		result = 37 * result
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + this.getAuthorityId();
		return result;
	}

}
