package database;

// Generated 2013/8/24 �W�� 12:19:13 by Hibernate Tools 3.4.0.CR1

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private String userId;
	private String userName;
	private String passwordCode;
	private String employeeId;
	private String vouchDrawNoId;
	private Integer contactId;

	public Users() {
	}

	public Users(String userId, String passwordCode) {
		this.userId = userId;
		this.passwordCode = passwordCode;
	}

	public Users(String userId, String userName, String passwordCode,
			String employeeId, String vouchDrawNoId, Integer contactId) {
		this.userId = userId;
		this.userName = userName;
		this.passwordCode = passwordCode;
		this.employeeId = employeeId;
		this.vouchDrawNoId = vouchDrawNoId;
		this.contactId = contactId;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPasswordCode() {
		return this.passwordCode;
	}

	public void setPasswordCode(String passwordCode) {
		this.passwordCode = passwordCode;
	}

	public String getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}

	public String getVouchDrawNoId() {
		return this.vouchDrawNoId;
	}

	public void setVouchDrawNoId(String vouchDrawNoId) {
		this.vouchDrawNoId = vouchDrawNoId;
	}

	public Integer getContactId() {
		return this.contactId;
	}

	public void setContactId(Integer contactId) {
		this.contactId = contactId;
	}

}
