package database;

// Generated 2013/8/24 �W�� 12:19:13 by Hibernate Tools 3.4.0.CR1

/**
 * Userauthority generated by hbm2java
 */
public class Userauthority implements java.io.Serializable {

	private UserauthorityId id;

	public Userauthority() {
	}

	public Userauthority(UserauthorityId id) {
		this.id = id;
	}

	public UserauthorityId getId() {
		return this.id;
	}

	public void setId(UserauthorityId id) {
		this.id = id;
	}

}
